version: '3'

# ==============================================
# ISMD Validator - Docker Compose Configuration
# ==============================================
# This file defines the base configuration for running the ISMD Validator locally.
# Production deployments use Azure Container Apps managed by Terraform.
#
# Environment Files:
# -----------------
# - docker-compose.dev.yml    : Development environment overrides
# - docker-compose.local.yml  : Local development with custom images
#
# Quick Start:
# -----------
# 1. Install Prerequisites:
#    - Docker Desktop (Windows/Mac) or Docker Engine (Linux)
#    - docker-compose (v2.0.0+)
#
# 2. Basic Usage:
#    # Start with production images (not for development):
#    docker compose up
#
#    # Development environment (recommended for local work):
#    docker compose -f docker-compose.yml -f docker-compose.dev.yml up
#
#    # Local development with custom built images:
#    docker compose -f docker-compose.yml -f docker-compose.dev.yml -f docker-compose.local.yml up
#
# 3. Access Applications:
#    - Frontend: http://localhost:3000
#    - Backend API: http://localhost:8080
#
# 4. Useful Commands:
#    # View logs (follow mode):
#    docker compose logs -f
#
#    # Rebuild and restart services:
#    docker compose up -d --build
#
#    # Stop all services:
#    docker compose down
#
# Environment Variables:
# ---------------------
# NEXT_PUBLIC_BE_URL: Backend API URL (default: http://localhost:8080)
# NODE_ENV: Node.js environment (development/production)
# SPRING_PROFILES_ACTIVE: Spring profile (localhost/development/production)
#
# Note: For production deployment, use Terraform configuration instead.
# ==============================================

services:
  ismd-validator-backend:
    image: ghcr.io/datagov-cz/ismd-validator-backend:latest
    container_name: ismd-validator-backend
    environment:
      - PORT=8080
      - SPRING_PROFILES_ACTIVE=production
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  ismd-validator-frontend:
    image: ghcr.io/datagov-cz/ismd-validator-frontend:latest
    container_name: ismd-validator-frontend
    environment:
      - NEXT_PUBLIC_BE_URL=http://localhost:8080
      - NODE_ENV=production
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    depends_on:
      - ismd-validator-backend
